/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.*;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Observable;
import java.util.Observer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Flavien
 */
public class ACStatus extends javax.swing.JPanel implements Simulable, Observer {

    public static final DecimalFormat strFormat = new DecimalFormat("#0.00");
    private AC ac;

    private String Pathhot;
    private String Pathcold;
    private ImageIcon hotImg;
    private ImageIcon coldImg;
    private BufferedImage tempHot;
    private BufferedImage tempCold;

    public static final int targetTemp = 10;
    protected boolean isACCold = true;

    /**
     * Creates new form ACStatus
     */
    public ACStatus(AC ac) {
        this.ac = ac;
        ac.addObserver(this);
        initComponents();
        try {
            Pathhot = getClass().getClassLoader().getResource("cold.png").getFile();
            Pathcold = getClass().getClassLoader().getResource("hot.png").getFile();
        } catch (Exception e) {
            e.printStackTrace();
        }
        updateData();
    }

    @Override
    public void updateData() {
        TempExtLabel.setText(strFormat.format(ac.temperatureExt));
        HumExtLabel.setText(strFormat.format(ac.humiExt));
        jLabel7.setText(strFormat.format(ac.tempSortie));
        jLabel9.setText(strFormat.format(ac.humiSortie));
        isACCold = (ac.temperatureExt > ac.tempSortie);
        autoResizeAC();
    }

    public void autoResizeAC() {
        try {
            BufferedImage BImgHot = ImageIO.read(new File(Pathhot));
            BImgHot = toBufferedImage(resize(BImgHot));
            hotImg = new ImageIcon(BImgHot);

            BufferedImage BImgCold = ImageIO.read(new File(Pathcold));
            BImgCold = toBufferedImage(resize(BImgCold));
            coldImg = new ImageIcon(BImgCold);
            this.updateAC();
        } catch (IOException ex) {
            ex.getMessage();
        }
    }

    public Image resize(BufferedImage I) {
        Dimension D = (this.imagePanel.getSize().height == 0) ? this.imagePanel.getPreferredSize() : this.imagePanel.getSize();
        int size = (D.height == D.width) ? D.height : (D.height < D.width) ? D.height : D.width;
        return I.getScaledInstance(size, size, Image.SCALE_SMOOTH);
    }

    public static BufferedImage toBufferedImage(Image img) {
        if (img instanceof BufferedImage) {
            return (BufferedImage) img;
        }

        // Create a buffered image with transparency
        BufferedImage bimage = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);

        // Draw the image on to the buffered image
        Graphics2D bGr = bimage.createGraphics();
        bGr.drawImage(img, 0, 0, null);
        bGr.dispose();

        // Return the buffered image
        return bimage;
    }

    public void updateAC() {
        try {
            if (isACCold) {
                this.imageLabel.setIcon(hotImg);
            } else {
                this.imageLabel.setIcon(coldImg);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        statusPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TempExtLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HumExtLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(FrameBasique.BackgroundColor);
        setMinimumSize(new java.awt.Dimension(225, 300));
        setPreferredSize(new java.awt.Dimension(225, 300));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(FrameBasique.BackgroundColor);
        topPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ventilation principale");
        topPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(topPanel, java.awt.BorderLayout.NORTH);

        mainPanel.setBackground(FrameBasique.BackgroundColor);
        mainPanel.setMinimumSize(new java.awt.Dimension(225, 112));
        mainPanel.setPreferredSize(new java.awt.Dimension(225, 286));
        mainPanel.setLayout(new java.awt.GridLayout(2, 1));

        imagePanel.setBackground(FrameBasique.BackgroundColor);
        imagePanel.setMinimumSize(new java.awt.Dimension(225, 56));
        imagePanel.setPreferredSize(new java.awt.Dimension(225, 143));
        imagePanel.setLayout(new java.awt.BorderLayout());

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagePanel.add(imageLabel, java.awt.BorderLayout.CENTER);

        mainPanel.add(imagePanel);

        statusPanel.setBackground(FrameBasique.BackgroundColor);
        statusPanel.setLayout(new java.awt.GridLayout(4, 2));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Température Ext.");
        statusPanel.add(jLabel2);

        TempExtLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TempExtLabel.setText("N/A");
        statusPanel.add(TempExtLabel);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Humidité Ext.");
        statusPanel.add(jLabel4);

        HumExtLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HumExtLabel.setText("N/A");
        statusPanel.add(HumExtLabel);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Température de sortie");
        statusPanel.add(jLabel6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("10°C");
        statusPanel.add(jLabel7);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Humidité de sortie");
        statusPanel.add(jLabel8);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("15%");
        statusPanel.add(jLabel9);

        mainPanel.add(statusPanel);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        autoResizeAC();
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HumExtLabel;
    private javax.swing.JLabel TempExtLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        updateData();
    }

}
