/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.*;

/**
 *
 * @author Flavien
 */
public class StatusSilo extends javax.swing.JFrame implements Simulable {

    private Silo silo;

    /**
     * Creates new form StatusSilo
     */
    public StatusSilo(Silo s) {
        this.silo = s;
        initComponents();
        updateData();
    }

    @Override
    public void updateData() {
        ACStatus acs = new ACStatus(silo.ac);
        this.ACPanel.removeAll();
        this.ACPanel.add(acs);
        this.CellPanel.removeAll();

        for (Cellule c : silo.getCellules()) {
            CellStatus cs = new CellStatus(c);
            this.CellPanel.add(cs);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ACPanel = new javax.swing.JPanel();
        CellPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1720, 530));

        ACPanel.setBackground(FrameBasique.BackgroundColor);
        ACPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(ACPanel, java.awt.BorderLayout.WEST);

        CellPanel.setBackground(FrameBasique.BackgroundColor);
        CellPanel.setLayout(new java.awt.GridLayout(2, 5));
        getContentPane().add(CellPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ACPanel;
    private javax.swing.JPanel CellPanel;
    // End of variables declaration//GEN-END:variables
}
